// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CloudQuotasLogging: CloudQuotasStub {
    let inner: any CloudQuotasStub
    let logger: Logger

    public init(_ inner: any CloudQuotasStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleApiCloudquotasV1"
      logger[metadataKey: "gcp.client.service"] = "cloudquotas"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudQuotas"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listQuotaInfos(
      request: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.ListQuotaInfosResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listQuotaInfos",
        action: {
          (r: ListQuotaInfosRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.ListQuotaInfosResponse
          in
          return try await self.inner.listQuotaInfos(request: r, options: o)
        })
    }

    public func getQuotaInfo(
      request: GetQuotaInfoRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaInfo {
      try await self._intercept(
        request: request,
        options: options,
        name: "getQuotaInfo",
        action: {
          (r: GetQuotaInfoRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaInfo
          in
          return try await self.inner.getQuotaInfo(request: r, options: o)
        })
    }

    public func listQuotaPreferences(
      request: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.ListQuotaPreferencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listQuotaPreferences",
        action: {
          (r: ListQuotaPreferencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.ListQuotaPreferencesResponse
          in
          return try await self.inner.listQuotaPreferences(request: r, options: o)
        })
    }

    public func getQuotaPreference(
      request: GetQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaPreference {
      try await self._intercept(
        request: request,
        options: options,
        name: "getQuotaPreference",
        action: {
          (r: GetQuotaPreferenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaPreference
          in
          return try await self.inner.getQuotaPreference(request: r, options: o)
        })
    }

    public func createQuotaPreference(
      request: CreateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaPreference {
      try await self._intercept(
        request: request,
        options: options,
        name: "createQuotaPreference",
        action: {
          (r: CreateQuotaPreferenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaPreference
          in
          return try await self.inner.createQuotaPreference(request: r, options: o)
        })
    }

    public func updateQuotaPreference(
      request: UpdateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaPreference {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateQuotaPreference",
        action: {
          (r: UpdateQuotaPreferenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaPreference
          in
          return try await self.inner.updateQuotaPreference(request: r, options: o)
        })
    }
  }
}
