// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// The Cloud Quotas API is an infrastructure service for Google Cloud that lets
/// service consumers list and manage their resource usage limits.
///
/// - List/Get the metadata and current status of the quotas for a service.
/// - Create/Update quota preferencess that declare the preferred quota values.
/// - Check the status of a quota preference request.
/// - List/Get pending and historical quota preference.
///
/// @Snippet(path: "CloudQuotasQuickstart")
public final class CloudQuotasClient: Clients.CloudQuotasProtocol, Sendable {
  let inner: any Clients.CloudQuotasStub

  /// Creates a new `CloudQuotasClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudQuotasStub = try Clients.CloudQuotasTransport(options)
    inner = Clients.CloudQuotasRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudQuotasLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists QuotaInfos of all quotas for a given project, folder or organization.
  ///
  /// @Snippet(path: "CloudQuotas_ListQuotaInfos")
  public func listQuotaInfos(
    request: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse {
    try await self.inner.listQuotaInfos(request: request, options: options)
  }

  /// Lists QuotaInfos of all quotas for a given project, folder or organization.
  ///
  /// @Snippet(path: "CloudQuotas_ListQuotaInfos")
  public func listQuotaInfos(
    byItem: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<QuotaInfo, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listQuotaInfos(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieve the QuotaInfo of a quota for a project, folder or organization.
  ///
  /// @Snippet(path: "CloudQuotas_GetQuotaInfo")
  public func getQuotaInfo(
    request: GetQuotaInfoRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaInfo {
    try await self.inner.getQuotaInfo(request: request, options: options)
  }

  /// Lists QuotaPreferences in a given project, folder or organization.
  ///
  /// @Snippet(path: "CloudQuotas_ListQuotaPreferences")
  public func listQuotaPreferences(
    request: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse {
    try await self.inner.listQuotaPreferences(request: request, options: options)
  }

  /// Lists QuotaPreferences in a given project, folder or organization.
  ///
  /// @Snippet(path: "CloudQuotas_ListQuotaPreferences")
  public func listQuotaPreferences(
    byItem: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<QuotaPreference, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listQuotaPreferences(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single QuotaPreference.
  ///
  /// @Snippet(path: "CloudQuotas_GetQuotaPreference")
  public func getQuotaPreference(
    request: GetQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    try await self.inner.getQuotaPreference(request: request, options: options)
  }

  /// Creates a new QuotaPreference that declares the desired value for a quota.
  ///
  /// @Snippet(path: "CloudQuotas_CreateQuotaPreference")
  public func createQuotaPreference(
    request: CreateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    try await self.inner.createQuotaPreference(request: request, options: options)
  }

  /// Updates the parameters of a single QuotaPreference. It can updates the
  /// config in any states, not just the ones pending approval.
  ///
  /// @Snippet(path: "CloudQuotas_UpdateQuotaPreference")
  public func updateQuotaPreference(
    request: UpdateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    try await self.inner.updateQuotaPreference(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudQuotasClient`.
  ///
  /// To mock `CloudQuotasClient` change your functions to receive
  /// `some CloudQuotasProtocol` or `any CloudQuotasProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudQuotasProtocol {
    /// See `CloudQuotasClient.listQuotaInfos`.
    func listQuotaInfos(request: ListQuotaInfosRequest) async throws
      -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse

    /// See `CloudQuotasClient.listQuotaInfos`.
    func listQuotaInfos(
      byItem: ListQuotaInfosRequest
    ) throws -> any AsyncSequence<QuotaInfo, Swift.Error>

    /// See `CloudQuotasClient.listQuotaInfos`.
    func listQuotaInfos(
      parent: Swift.String,
    ) throws -> any AsyncSequence<QuotaInfo, Swift.Error>

    /// See `CloudQuotasClient.getQuotaInfo`.
    func getQuotaInfo(request: GetQuotaInfoRequest) async throws -> GoogleApiCloudQuotasV1.QuotaInfo

    /// See `CloudQuotasClient.getQuotaInfo`.
    func getQuotaInfo(
      name: Swift.String,
    ) async throws -> GoogleApiCloudQuotasV1.QuotaInfo

    /// See `CloudQuotasClient.listQuotaPreferences`.
    func listQuotaPreferences(request: ListQuotaPreferencesRequest) async throws
      -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse

    /// See `CloudQuotasClient.listQuotaPreferences`.
    func listQuotaPreferences(
      byItem: ListQuotaPreferencesRequest
    ) throws -> any AsyncSequence<QuotaPreference, Swift.Error>

    /// See `CloudQuotasClient.listQuotaPreferences`.
    func listQuotaPreferences(
      parent: Swift.String,
    ) throws -> any AsyncSequence<QuotaPreference, Swift.Error>

    /// See `CloudQuotasClient.getQuotaPreference`.
    func getQuotaPreference(request: GetQuotaPreferenceRequest) async throws
      -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.getQuotaPreference`.
    func getQuotaPreference(
      name: Swift.String,
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.createQuotaPreference`.
    func createQuotaPreference(request: CreateQuotaPreferenceRequest) async throws
      -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.createQuotaPreference`.
    func createQuotaPreference(
      parent: Swift.String,
      quotaPreference: QuotaPreference?,
      quotaPreferenceId: Swift.String,
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.createQuotaPreference`.
    func createQuotaPreference(
      parent: Swift.String,
      quotaPreference: QuotaPreference?,
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.updateQuotaPreference`.
    func updateQuotaPreference(request: UpdateQuotaPreferenceRequest) async throws
      -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.updateQuotaPreference`.
    func updateQuotaPreference(
      quotaPreference: QuotaPreference?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.listQuotaInfos`.
    func listQuotaInfos(
      request: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse

    /// See `CloudQuotasClient.listQuotaInfos`.
    func listQuotaInfos(
      byItem: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<QuotaInfo, Swift.Error>

    /// See `CloudQuotasClient.getQuotaInfo`.
    func getQuotaInfo(
      request: GetQuotaInfoRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaInfo

    /// See `CloudQuotasClient.listQuotaPreferences`.
    func listQuotaPreferences(
      request: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse

    /// See `CloudQuotasClient.listQuotaPreferences`.
    func listQuotaPreferences(
      byItem: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<QuotaPreference, Swift.Error>

    /// See `CloudQuotasClient.getQuotaPreference`.
    func getQuotaPreference(
      request: GetQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.createQuotaPreference`.
    func createQuotaPreference(
      request: CreateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    /// See `CloudQuotasClient.updateQuotaPreference`.
    func updateQuotaPreference(
      request: UpdateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference
  }
}

// Default implementations
extension Clients.CloudQuotasProtocol {
  public func listQuotaInfos(request: ListQuotaInfosRequest) async throws
    -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse
  {
    try await self.listQuotaInfos(request: request, options: .init())
  }

  public func listQuotaInfos(
    request: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listQuotaInfos(
    byItem: ListQuotaInfosRequest
  ) throws -> any AsyncSequence<QuotaInfo, Swift.Error> {
    try self.listQuotaInfos(byItem: byItem, options: .init())
  }

  public func listQuotaInfos(
    byItem: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<QuotaInfo, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listQuotaInfos(
    parent: Swift.String,
  ) throws -> any AsyncSequence<QuotaInfo, Swift.Error> {
    let request = ListQuotaInfosRequest().with {
      $0.parent = parent
    }
    return try self.listQuotaInfos(byItem: request)
  }

  public func getQuotaInfo(request: GetQuotaInfoRequest) async throws
    -> GoogleApiCloudQuotasV1.QuotaInfo
  {
    try await self.getQuotaInfo(request: request, options: .init())
  }

  public func getQuotaInfo(
    request: GetQuotaInfoRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaInfo {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getQuotaInfo(
    name: Swift.String,
  ) async throws -> GoogleApiCloudQuotasV1.QuotaInfo {
    let request = GetQuotaInfoRequest().with {
      $0.name = name
    }
    return try await self.getQuotaInfo(request: request)
  }

  public func listQuotaPreferences(request: ListQuotaPreferencesRequest) async throws
    -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse
  {
    try await self.listQuotaPreferences(request: request, options: .init())
  }

  public func listQuotaPreferences(
    request: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listQuotaPreferences(
    byItem: ListQuotaPreferencesRequest
  ) throws -> any AsyncSequence<QuotaPreference, Swift.Error> {
    try self.listQuotaPreferences(byItem: byItem, options: .init())
  }

  public func listQuotaPreferences(
    byItem: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<QuotaPreference, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listQuotaPreferences(
    parent: Swift.String,
  ) throws -> any AsyncSequence<QuotaPreference, Swift.Error> {
    let request = ListQuotaPreferencesRequest().with {
      $0.parent = parent
    }
    return try self.listQuotaPreferences(byItem: request)
  }

  public func getQuotaPreference(request: GetQuotaPreferenceRequest) async throws
    -> GoogleApiCloudQuotasV1.QuotaPreference
  {
    try await self.getQuotaPreference(request: request, options: .init())
  }

  public func getQuotaPreference(
    request: GetQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getQuotaPreference(
    name: Swift.String,
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    let request = GetQuotaPreferenceRequest().with {
      $0.name = name
    }
    return try await self.getQuotaPreference(request: request)
  }

  public func createQuotaPreference(request: CreateQuotaPreferenceRequest) async throws
    -> GoogleApiCloudQuotasV1.QuotaPreference
  {
    try await self.createQuotaPreference(request: request, options: .init())
  }

  public func createQuotaPreference(
    request: CreateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createQuotaPreference(
    parent: Swift.String,
    quotaPreference: QuotaPreference?,
    quotaPreferenceId: Swift.String,
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    let request = CreateQuotaPreferenceRequest().with {
      $0.parent = parent
      $0.quotaPreference = quotaPreference
      $0.quotaPreferenceId = quotaPreferenceId
    }
    return try await self.createQuotaPreference(request: request)
  }

  public func createQuotaPreference(
    parent: Swift.String,
    quotaPreference: QuotaPreference?,
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    let request = CreateQuotaPreferenceRequest().with {
      $0.parent = parent
      $0.quotaPreference = quotaPreference
    }
    return try await self.createQuotaPreference(request: request)
  }

  public func updateQuotaPreference(request: UpdateQuotaPreferenceRequest) async throws
    -> GoogleApiCloudQuotasV1.QuotaPreference
  {
    try await self.updateQuotaPreference(request: request, options: .init())
  }

  public func updateQuotaPreference(
    request: UpdateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateQuotaPreference(
    quotaPreference: QuotaPreference?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference {
    let request = UpdateQuotaPreferenceRequest().with {
      $0.quotaPreference = quotaPreference
      $0.updateMask = updateMask
    }
    return try await self.updateQuotaPreference(request: request)
  }
}
