// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class CloudQuotasRetry: CloudQuotasStub {
    let inner: any CloudQuotasStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any CloudQuotasStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listQuotaInfos(
      request: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.ListQuotaInfosResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListQuotaInfosRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.ListQuotaInfosResponse
          in
          return try await self.inner.listQuotaInfos(request: r, options: o)
        })
    }

    public func getQuotaInfo(
      request: GetQuotaInfoRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaInfo {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetQuotaInfoRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaInfo
          in
          return try await self.inner.getQuotaInfo(request: r, options: o)
        })
    }

    public func listQuotaPreferences(
      request: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.ListQuotaPreferencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListQuotaPreferencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.ListQuotaPreferencesResponse
          in
          return try await self.inner.listQuotaPreferences(request: r, options: o)
        })
    }

    public func getQuotaPreference(
      request: GetQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaPreference {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetQuotaPreferenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaPreference
          in
          return try await self.inner.getQuotaPreference(request: r, options: o)
        })
    }

    public func createQuotaPreference(
      request: CreateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaPreference {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateQuotaPreferenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaPreference
          in
          return try await self.inner.createQuotaPreference(request: r, options: o)
        })
    }

    public func updateQuotaPreference(
      request: UpdateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaPreference {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateQuotaPreferenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiCloudquotasV1.QuotaPreference
          in
          return try await self.inner.updateQuotaPreference(request: r, options: o)
        })
    }
  }
}
