// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol CloudQuotasStub: Sendable {
    func listQuotaInfos(
      request: ListQuotaInfosRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.ListQuotaInfosResponse

    func getQuotaInfo(
      request: GetQuotaInfoRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaInfo

    func listQuotaPreferences(
      request: ListQuotaPreferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.ListQuotaPreferencesResponse

    func getQuotaPreference(
      request: GetQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    func createQuotaPreference(
      request: CreateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference

    func updateQuotaPreference(
      request: UpdateQuotaPreferenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudQuotasV1.QuotaPreference
  }
}
