// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message for creating a QuotaPreference
public struct CreateQuotaPreferenceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Identifier. Value for parent.
  ///
  /// Example:
  /// `projects/123/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Optional. Id of the requesting object, must be unique under its parent.
  /// If client does not set this field, the service will generate one.
  public var quotaPreferenceId: Swift.String = Swift.String()

  /// Required. The resource being created
  public var quotaPreference: QuotaPreference? = nil

  /// The list of quota safety checks to be ignored.
  public var ignoreSafetyChecks: [QuotaSafetyCheck] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateQuotaPreferenceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateQuotaPreferenceRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let quotaPreferenceId = CodingKeys(stringValue: "quotaPreferenceId")
    static let quotaPreference = CodingKeys(stringValue: "quotaPreference")
    static let ignoreSafetyChecks = CodingKeys(stringValue: "ignoreSafetyChecks")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "quotaPreferenceId",
      "quotaPreference",
      "ignoreSafetyChecks",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .quotaPreferenceId) {
      self.quotaPreferenceId = value
    }
    self.quotaPreference = try container.decodeIfPresent(
      QuotaPreference.self, forKey: .quotaPreference)
    if let value = try container.decodeIfPresent(
      [QuotaSafetyCheck].self, forKey: .ignoreSafetyChecks)
    {
      self.ignoreSafetyChecks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.quotaPreferenceId, forKey: .quotaPreferenceId)
    try container.encodeIfPresent(self.quotaPreference, forKey: .quotaPreference)
    try container.encode(self.ignoreSafetyChecks, forKey: .ignoreSafetyChecks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.cloudquotas.v1.CreateQuotaPreferenceRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
