// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The detailed quota information such as effective quota value for a
/// combination of dimensions.
public struct DimensionsInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The map of dimensions in key-value pairs. The key of a map entry
  /// is "region", "zone", or the name of a service-specific dimension, and the
  /// value of a map entry is the value of the dimension. If a dimension does
  /// not appear in the map of dimensions, the dimensions info applies to all
  /// the dimension values except for those that have another DimensionInfo
  /// instance configured for the specific value.
  /// For example: `{"provider" : "Example Organization"}` where `provider` is a
  /// service-specific quota dimension and `Example Organization` is the provider
  /// name.
  public var dimensions: [Swift.String: Swift.String] = [:]

  /// Quota details for the specified dimensions.
  public var details: QuotaDetails? = nil

  /// The applicable regions or zones of this dimension. The field is
  /// set to ['global'] for quotas that are not per region or per zone.
  /// Otherwise, it will be set to the list of locations this dimension info is
  /// applicable to.
  public var applicableLocations: [Swift.String] = []

  /// Initialize a new instance of `DimensionsInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DimensionsInfo().with { $0.dimensions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.cloudquotas.v1.DimensionsInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
