// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message for requesting list of QuotaPreferences
public struct ListQuotaPreferencesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parent value of QuotaPreference resources.
  /// Listing across different resource containers (such as 'projects/-') is not
  /// allowed.
  ///
  /// When the value starts with 'folders' or 'organizations', it lists the
  /// QuotaPreferences for org quotas in the container. It does not list the
  /// QuotaPreferences in the descendant projects of the container.
  ///
  /// Example parents:
  /// `projects/123/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Optional. Requested page size. Server may return fewer items than
  /// requested. If unspecified, server will pick an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Filter result QuotaPreferences by their state, type,
  /// create/update time range.
  ///
  /// Example filters:
  /// `reconciling=true AND request_type=CLOUD_CONSOLE`,
  /// `reconciling=true OR creation_time>2022-12-03T10:30:00`
  public var filter: Swift.String = Swift.String()

  /// Optional. How to order of the results. By default, the results are ordered
  /// by create time.
  ///
  /// Example orders:
  /// `quota_id`,
  /// `service, create_time`
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListQuotaPreferencesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListQuotaPreferencesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.cloudquotas.v1.ListQuotaPreferencesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
