// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The preferred quota configuration.
public struct QuotaConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The preferred value. Must be greater than or equal to -1. If set
  /// to -1, it means the value is "unlimited".
  public var preferredValue: Swift.Int64 = Swift.Int64()

  /// Output only. Optional details about the state of this quota preference.
  public var stateDetail: Swift.String = Swift.String()

  /// Output only. Granted quota value.
  public var grantedValue: GoogleCloudWkt.Int64Value? = nil

  /// Output only. The trace id that the Google Cloud uses to provision the
  /// requested quota. This trace id may be used by the client to contact Cloud
  /// support to track the state of a quota preference request. The trace id is
  /// only produced for increase requests and is unique for each request. The
  /// quota decrease requests do not have a trace id.
  public var traceId: Swift.String = Swift.String()

  /// Optional. The annotations map for clients to store small amounts of
  /// arbitrary data. Do not put PII or other sensitive information here. See
  /// https://google.aip.dev/128#annotations
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The origin of the quota preference request.
  public var requestOrigin: QuotaConfig.Origin = QuotaConfig.Origin()

  /// Initialize a new instance of `QuotaConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaConfig().with { $0.preferredValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The enumeration of the origins of quota preference requests.
  public enum Origin: Codable, Equatable, Sendable {
    /// The unspecified value.
    case unspecified
    /// Created through Cloud Console.
    case cloudConsole
    /// Generated by automatic quota adjustment.
    case autoAdjuster
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudConsole: return 1
      case .autoAdjuster: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ORIGIN_UNSPECIFIED"
      case .cloudConsole: return "CLOUD_CONSOLE"
      case .autoAdjuster: return "AUTO_ADJUSTER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ORIGIN_UNSPECIFIED": self = .unspecified
      case "CLOUD_CONSOLE": self = .cloudConsole
      case "AUTO_ADJUSTER": self = .autoAdjuster
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudConsole
      case 2: self = .autoAdjuster
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudConsole: return try container.encode(1)
      case .autoAdjuster: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.cloudquotas.v1.QuotaConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
