// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// QuotaInfo represents information about a particular quota for a given
/// project, folder or organization.
public struct QuotaInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Resource name of this QuotaInfo.
  /// The ID component following "locations/" must be "global".
  /// For example,
  /// `projects/123/locations/global/services/compute.googleapis.com/quotaInfos/CpusPerProjectPerRegion`
  public var name: Swift.String = Swift.String()

  /// The id of the quota, which is unique within the service.
  /// For example, `CpusPerProjectPerRegion`
  public var quotaId: Swift.String = Swift.String()

  /// The metric of the quota. It specifies the resources consumption the quota
  /// is defined for.
  /// For example, `compute.googleapis.com/cpus`
  public var metric: Swift.String = Swift.String()

  /// The name of the service in which the quota is defined.
  /// For example, `compute.googleapis.com`
  public var service: Swift.String = Swift.String()

  /// Whether this is a precise quota. A precise quota is tracked with absolute
  /// precision. In contrast, an imprecise quota is not tracked with precision.
  public var isPrecise: Swift.Bool = Swift.Bool()

  /// The reset time interval for the quota. Refresh interval applies to rate
  /// quota only.
  /// For example, "minute" for per minute, "day" for per day, or "10 seconds"
  /// for every 10 seconds.
  public var refreshInterval: Swift.String = Swift.String()

  /// The container type of the QuotaInfo.
  public var containerType: QuotaInfo.ContainerType = QuotaInfo.ContainerType()

  /// The dimensions the quota is defined on.
  public var dimensions: [Swift.String] = []

  /// The display name of the quota metric
  public var metricDisplayName: Swift.String = Swift.String()

  /// The display name of the quota.
  public var quotaDisplayName: Swift.String = Swift.String()

  /// The unit in which the metric value is reported, e.g., "MByte".
  public var metricUnit: Swift.String = Swift.String()

  /// Whether it is eligible to request a higher quota value for this quota.
  public var quotaIncreaseEligibility: QuotaIncreaseEligibility? = nil

  /// Whether the quota value is fixed or adjustable
  public var isFixed: Swift.Bool = Swift.Bool()

  /// The collection of dimensions info ordered by their dimensions from more
  /// specific ones to less specific ones.
  public var dimensionsInfos: [DimensionsInfo] = []

  /// Whether the quota is a concurrent quota. Concurrent quotas are enforced
  /// on the total number of concurrent operations in flight at any given time.
  public var isConcurrent: Swift.Bool = Swift.Bool()

  /// URI to the page where users can request more quota for the cloud
  /// service—for example,
  /// https://console.cloud.google.com/iam-admin/quotas.
  public var serviceRequestQuotaUri: Swift.String = Swift.String()

  /// Initialize a new instance of `QuotaInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaInfo().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The enumeration of the types of a cloud resource container.
  public enum ContainerType: Codable, Equatable, Sendable {
    /// Unspecified container type.
    case unspecified
    /// consumer project
    case project
    /// folder
    case folder
    /// organization
    case organization
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .project: return 1
      case .folder: return 2
      case .organization: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONTAINER_TYPE_UNSPECIFIED"
      case .project: return "PROJECT"
      case .folder: return "FOLDER"
      case .organization: return "ORGANIZATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContainerType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONTAINER_TYPE_UNSPECIFIED": self = .unspecified
      case "PROJECT": self = .project
      case "FOLDER": self = .folder
      case "ORGANIZATION": self = .organization
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContainerType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .project
      case 2: self = .folder
      case 3: self = .organization
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .project: return try container.encode(1)
      case .folder: return try container.encode(2)
      case .organization: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.cloudquotas.v1.QuotaInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
