// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// QuotaInfo represents information about a particular quota for a given
/// project, folder or organization.
public struct QuotaInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Resource name of this QuotaInfo.
  /// The ID component following "locations/" must be "global".
  /// For example,
  /// `projects/123/locations/global/services/compute.googleapis.com/quotaInfos/CpusPerProjectPerRegion`
  public var name: Swift.String = Swift.String()

  /// The id of the quota, which is unique within the service.
  /// For example, `CpusPerProjectPerRegion`
  public var quotaId: Swift.String = Swift.String()

  /// The metric of the quota. It specifies the resources consumption the quota
  /// is defined for.
  /// For example, `compute.googleapis.com/cpus`
  public var metric: Swift.String = Swift.String()

  /// The name of the service in which the quota is defined.
  /// For example, `compute.googleapis.com`
  public var service: Swift.String = Swift.String()

  /// Whether this is a precise quota. A precise quota is tracked with absolute
  /// precision. In contrast, an imprecise quota is not tracked with precision.
  public var isPrecise: Swift.Bool = Swift.Bool()

  /// The reset time interval for the quota. Refresh interval applies to rate
  /// quota only.
  /// For example, "minute" for per minute, "day" for per day, or "10 seconds"
  /// for every 10 seconds.
  public var refreshInterval: Swift.String = Swift.String()

  /// The container type of the QuotaInfo.
  public var containerType: QuotaInfo.ContainerType = QuotaInfo.ContainerType()

  /// The dimensions the quota is defined on.
  public var dimensions: [Swift.String] = []

  /// The display name of the quota metric
  public var metricDisplayName: Swift.String = Swift.String()

  /// The display name of the quota.
  public var quotaDisplayName: Swift.String = Swift.String()

  /// The unit in which the metric value is reported, e.g., "MByte".
  public var metricUnit: Swift.String = Swift.String()

  /// Whether it is eligible to request a higher quota value for this quota.
  public var quotaIncreaseEligibility: QuotaIncreaseEligibility? = nil

  /// Whether the quota value is fixed or adjustable
  public var isFixed: Swift.Bool = Swift.Bool()

  /// The collection of dimensions info ordered by their dimensions from more
  /// specific ones to less specific ones.
  public var dimensionsInfos: [DimensionsInfo] = []

  /// Whether the quota is a concurrent quota. Concurrent quotas are enforced
  /// on the total number of concurrent operations in flight at any given time.
  public var isConcurrent: Swift.Bool = Swift.Bool()

  /// URI to the page where users can request more quota for the cloud
  /// service—for example,
  /// https://console.cloud.google.com/iam-admin/quotas.
  public var serviceRequestQuotaUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QuotaInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaInfo().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let quotaId = CodingKeys(stringValue: "quotaId")
    static let metric = CodingKeys(stringValue: "metric")
    static let service = CodingKeys(stringValue: "service")
    static let isPrecise = CodingKeys(stringValue: "isPrecise")
    static let refreshInterval = CodingKeys(stringValue: "refreshInterval")
    static let containerType = CodingKeys(stringValue: "containerType")
    static let dimensions = CodingKeys(stringValue: "dimensions")
    static let metricDisplayName = CodingKeys(stringValue: "metricDisplayName")
    static let quotaDisplayName = CodingKeys(stringValue: "quotaDisplayName")
    static let metricUnit = CodingKeys(stringValue: "metricUnit")
    static let quotaIncreaseEligibility = CodingKeys(stringValue: "quotaIncreaseEligibility")
    static let isFixed = CodingKeys(stringValue: "isFixed")
    static let dimensionsInfos = CodingKeys(stringValue: "dimensionsInfos")
    static let isConcurrent = CodingKeys(stringValue: "isConcurrent")
    static let serviceRequestQuotaUri = CodingKeys(stringValue: "serviceRequestQuotaUri")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "quotaId",
      "metric",
      "service",
      "isPrecise",
      "refreshInterval",
      "containerType",
      "dimensions",
      "metricDisplayName",
      "quotaDisplayName",
      "metricUnit",
      "quotaIncreaseEligibility",
      "isFixed",
      "dimensionsInfos",
      "isConcurrent",
      "serviceRequestQuotaUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .quotaId) {
      self.quotaId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .metric) {
      self.metric = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .service) {
      self.service = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isPrecise) {
      self.isPrecise = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .refreshInterval) {
      self.refreshInterval = value
    }
    if let value = try container.decodeIfPresent(
      QuotaInfo.ContainerType.self, forKey: .containerType)
    {
      self.containerType = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .dimensions) {
      self.dimensions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .metricDisplayName) {
      self.metricDisplayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .quotaDisplayName) {
      self.quotaDisplayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .metricUnit) {
      self.metricUnit = value
    }
    self.quotaIncreaseEligibility = try container.decodeIfPresent(
      QuotaIncreaseEligibility.self, forKey: .quotaIncreaseEligibility)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isFixed) {
      self.isFixed = value
    }
    if let value = try container.decodeIfPresent([DimensionsInfo].self, forKey: .dimensionsInfos) {
      self.dimensionsInfos = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isConcurrent) {
      self.isConcurrent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceRequestQuotaUri)
    {
      self.serviceRequestQuotaUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.quotaId, forKey: .quotaId)
    try container.encode(self.metric, forKey: .metric)
    try container.encode(self.service, forKey: .service)
    try container.encode(self.isPrecise, forKey: .isPrecise)
    try container.encode(self.refreshInterval, forKey: .refreshInterval)
    try container.encode(self.containerType, forKey: .containerType)
    try container.encode(self.dimensions, forKey: .dimensions)
    try container.encode(self.metricDisplayName, forKey: .metricDisplayName)
    try container.encode(self.quotaDisplayName, forKey: .quotaDisplayName)
    try container.encode(self.metricUnit, forKey: .metricUnit)
    try container.encodeIfPresent(self.quotaIncreaseEligibility, forKey: .quotaIncreaseEligibility)
    try container.encode(self.isFixed, forKey: .isFixed)
    try container.encode(self.dimensionsInfos, forKey: .dimensionsInfos)
    try container.encode(self.isConcurrent, forKey: .isConcurrent)
    try container.encode(self.serviceRequestQuotaUri, forKey: .serviceRequestQuotaUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The enumeration of the types of a cloud resource container.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ContainerType: Codable, Equatable, Sendable {
    /// Unspecified container type.
    case unspecified
    /// consumer project
    case project
    /// folder
    case folder
    /// organization
    case organization
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .project: return 1
      case .folder: return 2
      case .organization: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONTAINER_TYPE_UNSPECIFIED"
      case .project: return "PROJECT"
      case .folder: return "FOLDER"
      case .organization: return "ORGANIZATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ContainerType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONTAINER_TYPE_UNSPECIFIED": self = .unspecified
      case "PROJECT": self = .project
      case "FOLDER": self = .folder
      case "ORGANIZATION": self = .organization
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ContainerType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .project
      case 2: self = .folder
      case 3: self = .organization
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CONTAINER_TYPE_UNSPECIFIED")
      case .project: return try container.encode("PROJECT")
      case .folder: return try container.encode("FOLDER")
      case .organization: return try container.encode("ORGANIZATION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.cloudquotas.v1.QuotaInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
