// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// The Quotas Adjuster Settings API is an infrastructure service for Google
///  Cloud that lets service consumers view and update their quota adjuster
///  settings.
///
/// - Update quota adjuster settings.
/// - Get the name of the configurations.
///
/// @Snippet(path: "QuotaAdjusterSettingsManagerQuickstart")
public class QuotaAdjusterSettingsManagerClient: Clients.QuotaAdjusterSettingsManagerProtocol {
  let inner: any Clients.QuotaAdjusterSettingsManagerStub

  /// Creates a new `QuotaAdjusterSettingsManagerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.QuotaAdjusterSettingsManagerStub =
      try Clients.QuotaAdjusterSettingsManagerTransport(options)
    inner = Clients.QuotaAdjusterSettingsManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.QuotaAdjusterSettingsManagerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Updates the QuotaAdjusterSettings for the specified resource.
  ///
  /// @Snippet(path: "QuotaAdjusterSettingsManager_UpdateQuotaAdjusterSettings")
  public func updateQuotaAdjusterSettings(
    request: UpdateQuotaAdjusterSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings {
    try await self.inner.updateQuotaAdjusterSettings(request: request, options: options)
  }

  /// Gets the QuotaAdjusterSettings for the specified resource.
  ///
  /// @Snippet(path: "QuotaAdjusterSettingsManager_GetQuotaAdjusterSettings")
  public func getQuotaAdjusterSettings(
    request: GetQuotaAdjusterSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings {
    try await self.inner.getQuotaAdjusterSettings(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `QuotaAdjusterSettingsManagerClient`.
  ///
  /// To mock `QuotaAdjusterSettingsManagerClient` change your functions to receive
  /// `some QuotaAdjusterSettingsManagerProtocol` or `any QuotaAdjusterSettingsManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol QuotaAdjusterSettingsManagerProtocol {
    /// See `QuotaAdjusterSettingsManagerClient.updateQuotaAdjusterSettings`.
    func updateQuotaAdjusterSettings(request: UpdateQuotaAdjusterSettingsRequest) async throws
      -> GoogleApiCloudquotasV1.QuotaAdjusterSettings

    /// See `QuotaAdjusterSettingsManagerClient.updateQuotaAdjusterSettings`.
    func updateQuotaAdjusterSettings(
      quotaAdjusterSettings: QuotaAdjusterSettings?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings

    /// See `QuotaAdjusterSettingsManagerClient.getQuotaAdjusterSettings`.
    func getQuotaAdjusterSettings(request: GetQuotaAdjusterSettingsRequest) async throws
      -> GoogleApiCloudquotasV1.QuotaAdjusterSettings

    /// See `QuotaAdjusterSettingsManagerClient.getQuotaAdjusterSettings`.
    func getQuotaAdjusterSettings(
      name: Swift.String,
    ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings

    /// See `QuotaAdjusterSettingsManagerClient.updateQuotaAdjusterSettings`.
    func updateQuotaAdjusterSettings(
      request: UpdateQuotaAdjusterSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings

    /// See `QuotaAdjusterSettingsManagerClient.getQuotaAdjusterSettings`.
    func getQuotaAdjusterSettings(
      request: GetQuotaAdjusterSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings
  }
}

// Default implementations
extension Clients.QuotaAdjusterSettingsManagerProtocol {
  public func updateQuotaAdjusterSettings(request: UpdateQuotaAdjusterSettingsRequest) async throws
    -> GoogleApiCloudquotasV1.QuotaAdjusterSettings
  {
    try await self.updateQuotaAdjusterSettings(request: request, options: .init())
  }

  public func updateQuotaAdjusterSettings(
    request: UpdateQuotaAdjusterSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateQuotaAdjusterSettings(
    quotaAdjusterSettings: QuotaAdjusterSettings?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings {
    let request = UpdateQuotaAdjusterSettingsRequest().with {
      $0.quotaAdjusterSettings = quotaAdjusterSettings
      $0.updateMask = updateMask
    }
    return try await self.updateQuotaAdjusterSettings(request: request)
  }

  public func getQuotaAdjusterSettings(request: GetQuotaAdjusterSettingsRequest) async throws
    -> GoogleApiCloudquotasV1.QuotaAdjusterSettings
  {
    try await self.getQuotaAdjusterSettings(request: request, options: .init())
  }

  public func getQuotaAdjusterSettings(
    request: GetQuotaAdjusterSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getQuotaAdjusterSettings(
    name: Swift.String,
  ) async throws -> GoogleApiCloudquotasV1.QuotaAdjusterSettings {
    let request = GetQuotaAdjusterSettingsRequest().with {
      $0.name = name
    }
    return try await self.getQuotaAdjusterSettings(request: request)
  }
}
