// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Eligibility information regarding requesting increase adjustment of a quota.
public struct QuotaIncreaseEligibility: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Whether a higher quota value can be requested for the quota.
  public var isEligible: Swift.Bool = Swift.Bool()

  /// The reason of why it is ineligible to request increased value of the quota.
  /// If the is_eligible field is true, it defaults to
  /// INELIGIBILITY_REASON_UNSPECIFIED.
  public var ineligibilityReason: QuotaIncreaseEligibility.IneligibilityReason =
    QuotaIncreaseEligibility.IneligibilityReason()

  /// Initialize a new instance of `QuotaIncreaseEligibility`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaIncreaseEligibility().with { $0.isEligible = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The enumeration of reasons when it is ineligible to request increase
  /// adjustment.
  public enum IneligibilityReason: Codable, Equatable, Sendable {
    /// Default value when is_eligible is true.
    case unspecified
    /// The container is not linked with a valid billing account.
    case noValidBillingAccount
    /// Other reasons.
    case other
    /// Quota increase is not supported for the quota.
    case notSupported
    /// There is not enough usage history to determine the eligibility.
    case notEnoughUsageHistory
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .noValidBillingAccount: return 1
      case .other: return 2
      case .notSupported: return 3
      case .notEnoughUsageHistory: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "INELIGIBILITY_REASON_UNSPECIFIED"
      case .noValidBillingAccount: return "NO_VALID_BILLING_ACCOUNT"
      case .other: return "OTHER"
      case .notSupported: return "NOT_SUPPORTED"
      case .notEnoughUsageHistory: return "NOT_ENOUGH_USAGE_HISTORY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "INELIGIBILITY_REASON_UNSPECIFIED": self = .unspecified
      case "NO_VALID_BILLING_ACCOUNT": self = .noValidBillingAccount
      case "NOT_SUPPORTED": self = .notSupported
      case "NOT_ENOUGH_USAGE_HISTORY": self = .notEnoughUsageHistory
      case "OTHER": self = .other
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .noValidBillingAccount
      case 3: self = .notSupported
      case 4: self = .notEnoughUsageHistory
      case 2: self = .other
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .noValidBillingAccount: return try container.encode(1)
      case .other: return try container.encode(2)
      case .notSupported: return try container.encode(3)
      case .notEnoughUsageHistory: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.api.cloudquotas.v1.QuotaIncreaseEligibility"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
