// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for updating a QuotaPreference
public struct UpdateQuotaPreferenceRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Field mask is used to specify the fields to be overwritten in the
  /// QuotaPreference resource by the update.
  /// The fields specified in the update_mask are relative to the resource, not
  /// the full request. A field will be overwritten if it is in the mask. If the
  /// user does not provide a mask then all fields will be overwritten.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// Required. The resource being updated
  public var quotaPreference: QuotaPreference? = nil

  /// Optional. If set to true, and the quota preference is not found, a new one
  /// will be created. In this situation, `update_mask` is ignored.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Optional. If set to true, validate the request, but do not actually update.
  /// Note that a request being valid does not mean that the request is
  /// guaranteed to be fulfilled.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// The list of quota safety checks to be ignored.
  public var ignoreSafetyChecks: [QuotaSafetyCheck] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateQuotaPreferenceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateQuotaPreferenceRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let quotaPreference = CodingKeys(stringValue: "quotaPreference")
    static let allowMissing = CodingKeys(stringValue: "allowMissing")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let ignoreSafetyChecks = CodingKeys(stringValue: "ignoreSafetyChecks")

    static let _knownKeys: Set<Swift.String> = [
      "updateMask",
      "quotaPreference",
      "allowMissing",
      "validateOnly",
      "ignoreSafetyChecks",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.updateMask = try container.decodeIfPresent(
      GoogleCloudWKT.FieldMask.self, forKey: .updateMask)
    self.quotaPreference = try container.decodeIfPresent(
      QuotaPreference.self, forKey: .quotaPreference)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowMissing) {
      self.allowMissing = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    if let value = try container.decodeIfPresent(
      [QuotaSafetyCheck].self, forKey: .ignoreSafetyChecks)
    {
      self.ignoreSafetyChecks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.quotaPreference, forKey: .quotaPreference)
    try container.encode(self.allowMissing, forKey: .allowMissing)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encode(self.ignoreSafetyChecks, forKey: .ignoreSafetyChecks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.cloudquotas.v1.UpdateQuotaPreferenceRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
